name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. Checkout del c贸digo
      uses: actions/checkout@v3

    - name: 2. Configurar Node.js
      uses: actions/setup-node@v3 
      with:
        node-version: '18'

    - name: 3. Instalar dependencias
      [cite_start]run: npm ci 
    - name: 4. Ejecutar tests con Jasmine/Karma
      [cite_start]run: npm test 

    - name: 5. Analizar c贸digo con ESLint
      [cite_start]run: npm run lint 

    - name: 6. Analizar vulnerabilidades con Snyk
      [cite_start]uses: snyk/actions/setup@v1 
    - [cite_start]run: snyk test --all-projects 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: 7. Analizar calidad con SonarCloud
      [cite_start]uses: SonarSource/sonarcloud-github-action@master 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push-docker:
    needs: build-and-test 
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout del c贸digo
      uses: actions/checkout@v3

    - name: 2. Iniciar sesi贸n en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 3. Construir y subir imagen a Docker Hub
      [cite_start]uses: docker/build-push-action@v4 
      with:
        context: .
        [cite_start]push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-nodejs:latest 
